# Generated by Django 5.2.6 on 2025-09-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otp',
            name='accounts_ot_phone_d789b1_idx',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
